---
# tasks file for roles

  - include_tasks: apache2.yaml
    when: ansible_facts['os_family'] == "Debian"
  - include_tasks: redhat.yaml
    when: ansible_facts['os_family'] == 'redhat'

  - name: copy the website file
    ansible.builtin.template:
      src: index.html.j2
      dest: "{{ doc_root }}/index.html"

  - include_tasks: mysql.yaml


  - name: copy the my.cnf file
    ansible.builtin.copy:
      src: .my.cnf
      dest: /home/Tom/.my.cnf
      mode: 0600
      owner: Tom
      group: Tom